language: ruby
services:
  - redis-server
rvm:
  - 2.3.8
  - 2.5.7
gemfile:
  - gemfiles/rails_6.x.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_4.2.gemfile
matrix:
  exclude:
    # Rails 6 & sidekiq 6 incompatible with ruby 2.3
  - rvm: 2.3.8
    gemfile: gemfiles/rails_6.x.gemfile
jobs:
  include:
    - stage: lint
      script:
        - bundle exec rubocop
      # Keep in mind to overwrite these here
      rvm: 2.5
      gemfile: gemfiles/rails_5.2.gemfile
